name: Cypress Tests with installation job

on: [push]

jobs:
    install:
        runs-on: ubuntu-latest
        container:
            image: cypress/browsers:node16.13.2-chrome100-ff98
            # NOTE: Necessary to avoid permissions issues
            # https://github.com/cypress-io/github-action/issues/446#issuecomment-987015822
            options: --user 1001
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Cypress install
              uses: cypress-io/github-action@v2
              with:
                  # Disable running of tests within install job
                  runTests: false
                  build: yarn build

            - name: Save build folder
              uses: actions/upload-artifact@v2
              with:
                  name: dist
                  if-no-files-found: error
                  path: dist

    cypress-run:
        runs-on: ubuntu-latest
        container:
            image: cypress/browsers:node16.13.2-chrome100-ff98
            options: --user 1001
        needs: install
        strategy:
            fail-fast: false
            matrix:
                # run copies of the current job in parallel
                containers: [1, 2, 3, 4, 5]
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install vite
              run: "yarn add vite -g"

            - name: Download the build folders
              uses: actions/download-artifact@v2
              with:
                  name: dist
                  path: dist

            # Install NPM dependencies, cache them correctly
            # and run all Cypress tests
            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  install: false
                  start: yarn preview
                  wait-on: "http://localhost:5050"
                  wait-on-timeout: 120
                  browser: chrome
                  record: true
                  parallel: true
                  group: "UI - Chrome"
              env:
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
